[package]
name = "busperf"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
pyo3 = { version = "0.25.1", features = ["auto-initialize"] }
tabled = "0.20.0"
wellen = "0.17.1"
yaml-rust2 = "0.10.3"
