[graph]

[output]
feature-depth = 1

[advisories]
[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "Unicode-3.0"
]
confidence-threshold = 0.8
exceptions = [
    { allow = ["Zlib"], crate = "foldhash" },
    { allow = ["BSD-3-Clause"], crate = "wellen" },
    { allow = ["BSD-3-Clause"], crate = "fst-reader" },
    { allow = ["BSD-3-Clause"], crate = "encoding_rs" },
    { allow = ["BSD-2-Clause"], crate = "arrayref" },
    { allow = ["BSL-1.0"], crate = "clipboard-win" },
    { allow = ["OFL-1.1", "Ubuntu-font-1.0"], crate = "epaint_default_fonts" },
    { allow = ["BSL-1.0"], crate = "error-code" },
    { allow = ["ISC"], crate = "libloading" },
    { allow = ["ISC"], crate = "is_ci" },
    { allow = ["Zlib"], crate = "slotmap" },
    { allow = ["BSD-3-Clause"], crate = "tiny-skia-path" },
    { allow = ["BSD-3-Clause"], crate = "tiny-skia" },
]

[bans]
multiple-versions = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
